spring:
  datasource:
    url: jdbc:mysql://mysql-launch:3307/launch_db
    username: launch_user
    password: launch_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8081
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html